### PR TITLE
Prefer order key over order id on the client

### PR DESCRIPTION
**Pull request by mntzrr**

### CODE REVIEW

**Comment by mntzrr** [comment]
Task linked: [CU-869338h3d Fix AJAX error messages](https://app.clickup.com/t/869338h3d)

**Comment by fitimvata** [comment]
@mntzrr This change may work for small database but for large database + high traffic `wc_get_order_id_by_order_key` takes very long

Im my case around 5.6s

Screenshot 2023-11-16 at 11 13 58 AM

**Comment by MichaelBengtsson** [comment]
> @mntzrr This change may work for small database but for large database + high traffic `wc_get_order_id_by_order_key` takes very long
> 
> Im my case around 5.6s
> 
> Screenshot 2023-11-16 at 11 13 58 AM

Thank you for the information, i did attempt this on a somewhat heavy database, where we had over a million records in our table. And the query for me was less then a second in that case. Even without HPOS enabled.

I know the query for this using HPOS is much quicker, and does not do a meta key lookup like the old query does. 
[New query](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L933-L938)

But we will look at seeing what other options we have for this, that would not require a meta key lookup in this way.

**Comment by fitimvata** [comment]
@MichaelBengtsson Another solution will be to use both. 
Get the order by order_id and compare order key with provided key.

```
$order_id = $_GET['order_id'];
$order_key = $_GET['order_key'];
$order = wc_get_order($order_id);
$order_key === $order->get_order_key();

```

This way its fast and secure.

**Comment by MichaelBengtsson** [comment]
@fitimvata Yes that is actually a very good and simple solution. Thank you for the suggestion!

@mntzrr Can you look into making that change in that case?

**Review by MichaelBengtsson — APPROVED** [review]

**Pull request merged**
